[tox]
envlist =
    py3{12}{,-casa,-pipeline}{,-oldestdeps,-cov}
    lint
    docs
requires =
    tox-uv
isolated_build = true

[gh]
python =
    3.12 = py312, lint, docs

# Run the main test suite
[testenv]
set_env =

    # Set various CASA paths
    CASASITECONFIG = {toxinidir}{/}.tmp{/}{envname}{/}.casa{/}config.py
    CASADIR = {toxinidir}{/}.tmp{/}.casa
    ENVDIR =  {toxinidir}{/}.tmp{/}{envname}
    CASACONFIGDIR = {toxinidir}{/}tests{/}casa_config_files

    # Set platform
    PLATFORM = unknown
    linux: PLATFORM = linux
    darwin: PLATFORM = mac
    win32: PLATFORM = windows

allowlist_externals =
    cp
    dot
    echo
    mkdir
    rm
    tar
    uvx
description =
    run tests
    casa: with CASA packages enabled
    pipeline: with CASA + pipeline packages enabled
    oldestdeps: with the oldest supported dependencies
    cov: with coverage
deps =
    oldestdeps: minimum_dependencies
extras =
    casa: casa
    pipeline: pipeline
    test
    casa,pipeline: test-casa
commands =

    echo Running on {env:PLATFORM}

    # If using CASA or the pipeline extra, create a temp directory to install data
    casa,pipeline: rm -rf {env:ENVDIR}
    casa,pipeline: mkdir -p {env:ENVDIR}

    # Move CASA startup files
    casa,pipeline: mkdir -p {env:ENVDIR}{/}.casa
    casa,pipeline: cp {env:CASACONFIGDIR}{/}startup.py {env:ENVDIR}{/}.casa{/}
    casa,pipeline: cp {env:CASACONFIGDIR}{/}config.py {env:ENVDIR}{/}.casa{/}

    # Download CASA data
    casa,pipeline: mkdir -p {env:CASADIR}{/}data
    casa,pipeline: python -m casaconfig --update-all
    casa,pipeline: python -m casaconfig --current-data

    # Download and extract the latest analysisUtils
    casa,pipeline: uvx zenodo_get 10.5281/zenodo.7502159 -o {env:ENVDIR}
    casa,pipeline: tar -xf {env:ENVDIR}{/}analysis_scripts.tar -C {env:ENVDIR}{/}

    {list_dependencies_command}

    # Run tests
    !casa-!pipeline: pytest -m "not casa" \
    casa-!pipeline: pytest -m "not pipeline" \
    pipeline: pytest \
    cov: --cov --cov-branch --cov-report=xml:{env:PLATFORM}-{envname}-coverage.xml \
    cov: --junitxml={env:PLATFORM}-{envname}-junit.xml -o junit_family=legacy \
    {posargs}

# Run lint
[testenv:lint]
description = run linters
extras =
    test-ruff
# --exit-zero here to not fail, since there's currently a
# lot of tidying to do
commands = ruff check {posargs} --exit-zero

# Build documentation
[testenv:docs]
changedir =
    docs
description =
    invoke sphinx-build to build docs, check links, report coverage
extras =
    docs
commands =
    echo Building docs
    sphinx-build -W -b html . _build/html {posargs}
    echo Checking links
    sphinx-build -W -b linkcheck . _build/linkcheck {posargs}
    echo Checking coverage
    sphinx-build -W -b coverage . _build/coverage {posargs}
